# Website Configuration
site:
  title: "React Docs UI Example"
  description: "Example documentation website built with React Docs UI"
  # Logo formats supported:
  # 1. emoji: "🤖"
  # 2. image URL: "https://example.com/logo.png"
  # 3. local image: "/images/logo.png"
  # 4. relative path: "./assets/logo.svg"
  logo:
    light: "/images/favicon.svg"
    dark: "/images/favicon-dark.svg"
  author: "React Docs UI Team"
  
# Navigation Bar Configuration
navbar:
  showLogo: true
  showTitle: true
  showLanguageSwitcher: true
  items:
    - title: "Home"
      link: "/"
      active: true
    - title: "Guide"
      link: "/guide"
  actions:
    - type: "github"
      link: "https://github.com/shenjianZ/React-docs-ui"
      enabled: true

# Sidebar Navigation Configuration
sidebar:
  enabled: true
  collections:
    guide:
      sections:
        - title: "Getting Started"
          path: "/guide"
          children:
            - title: "Introduction"
              path: "/guide/introduction"
            - title: "Installation"
              path: "/guide/installation"
            - title: "Quick Start"
              path: "/guide/quick-start"
            - title: "Configuration"
              path: "/guide/configuration"
          

# Theme Configuration
theme:
  # Default theme mode: 'light' | 'dark' | 'auto'
  # light: Force light mode
  # dark: Force dark mode
  # auto: Follow system preference (default)
  defaultMode: "auto"
  
  # Allow users to toggle theme (show theme toggle button)
  allowToggle: true
  

# Table of Contents Configuration
toc:
  # Maximum heading level to display in TOC (1-6)
  maxLevel: 3
  
  # Enable table of contents
  enabled: true
  
  # TOC title
  title: "On This Page" 

# Footer Configuration
footer:
  enabled: true
  copyright: "© 2024 React Docs UI. All rights reserved."
  repository:
    url: "https://github.com/your_github_id/your_repo_name"
    branch: "master"
  lastUpdated: "2024-12-19"
  links:
    - title: "Documentation"
      link: "/guide/introduction"
    - title: "GitHub"
      link: "https://github.com/your_github_id/your_repo_name"
      external: true
    - title: "License"
      link: "/license"
  social:
    - name: "email"
      url: "mailto:contact@example.com"
      icon: "mail"
    - name: "github"
      url: "https://github.com/your_github_id"
      icon: "github"
    # - name: "youtube"
    #   url: "https://youtube.com/@yourhandle"
    #   icon: "youtube"
    # - name: "twitter"
    #   url: "https://twitter.com/yourhandle"
    #   icon: "twitter"
    # - name: "discord"
    #   url: "https://discord.gg/yourinvite"
    #   icon: "discord"
    # - name: "telegram"
    #   url: "https://t.me/yourhandle"
    #   icon: "telegram"
    # - name: "tiktok"
    #   url: "https://tiktok.com/@yourhandle"
    #   icon: "tiktok"
    - name: "bilibili"
      url: "https://space.bilibili.com/your_bilibili_id"
      icon: "bilibili"
    - name: "qq"
      url: "mqqapi://card/show_pslcard?src_type=internal&version=1&uin=your_qq_id&card_type=person&source=qrcode"
      icon: "qq"
    - name: "wechat"
      url: "weixin://dl/add?your_wechat_id"
      icon: "wechat"
    # - name: "weibo"
    #   url: "https://weibo.com/yourhandle"
    #   icon: "weibo"
    # - name: "douyin"
    #   url: "https://www.douyin.com/user/yourhandle"
    #   icon: "douyin"
    # - name: "zhihu"
    #   url: "https://www.zhihu.com/people/yourhandle"
    #   icon: "zhihu" 

# PWA Configuration
pwa:
  enabled: false
  name: "React Docs UI"
  shortName: "ReactDocsUI"
  description: "Beautiful documentation websites made simple"
  themeColor: "#ffffff"
  backgroundColor: "#ffffff" 